<?xml version="1.0" encoding="utf-8"?><Database Class="ApplicationDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="" Member="DbUsers">
    <Type Name="DbUser">
      <Column Member="Name" Type="System.String" CanBeNull="false" />
      <Column Member="Age" Type="System.Int32" CanBeNull="false" />
      <Column Member="Id" Type="System.Guid" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>